// src/Canvas.jsx
import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import * as fabric from "fabric";

const page = { padding: 24, fontFamily: "system-ui" };
const toolBarStyle = { display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" };
const btn = (active) => ({
  padding: "10px 14px",
    border: active ? "2px solid #333" : "1px solid #ccc",
      background: active ? "#eee" : "#fff",
        borderRadius: 6,
        });

        // Tool names as constants — a typo now fails loudly instead of silently.
        const TOOLS = { SELECT: "select", BRUSH: "brush", LASSO: "lasso" };

        let uidCounter = 0;
        const nextUid = () => `obj_${++uidCounter}`;

        export default function Canvas() {
          const canvasElRef = useRef(null);
            const fabricCanvasRef = useRef(null);
              const wrapperRef = useRef(null);
                const [status, setStatus] = useState("Initializing…");
                  const [tool, setTool] = useState(TOOLS.BRUSH);
                    const [layers, setLayers] = useState([]);

                      useEffect(() => {
                          let canvas = null;
                              const width = wrapperRef.current?.clientWidth || 320;
                                  const height = Math.round(width * 1.4);

                                      try {
                                            canvas = new fabric.Canvas(canvasElRef.current, {
                                                    width,
                                                            height,
                                                                    backgroundColor: "#ffffff",
                                                                            enableRetinaScaling: true,
                                                                                    isDrawingMode: true,
                                                                                            selection: false,
                                                                                                  });

                                                                                                        canvas.freeDrawingBrush = new fabric.PencilBrush(canvas);
                                                                                                              canvas.freeDrawingBrush.width = 4;
                                                                                                                    canvas.freeDrawingBrush.color = "#111111";

                                                                                                                          fabricCanvasRef.current = canvas;

                                                                                                                                const refreshLayers = () => {
                                                                                                                                        setLayers(canvas.getObjects().map((o) => {
                                                                                                                                                  // Stable id assigned once, survives deletion and reordering.
                                                                                                                                                            if (!o.uid) o.uid = nextUid();
                                                                                                                                                                      return { uid: o.uid, type: o.type };
                                                                                                                                                                              }));
                                                                                                                                                                                    };
                                                                                                                                                                                          canvas.on("object:added", refreshLayers);
                                                                                                                                                                                                canvas.on("object:removed", refreshLayers);

                                                                                                                                                                                                      setStatus(`Ready — ${width}×${height}. Brush active.`);
                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                setStatus(`Canvas failed: ${err.name} — ${err.message}`);
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        return () => {
                                                                                                                                                                                                                              fabricCanvasRef.current = null;
                                                                                                                                                                                                                                    Promise.resolve(canvas?.dispose()).catch(() => {});
                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                                const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                    if (!c) return;

                                                                                                                                                                                                                                                        switch (tool) {
                                                                                                                                                                                                                                                              case TOOLS.BRUSH:
                                                                                                                                                                                                                                                                      c.isDrawingMode = true;
                                                                                                                                                                                                                                                                              c.selection = false;
                                                                                                                                                                                                                                                                                      setStatus("Brush — drag to draw.");
                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                    case TOOLS.SELECT:
                                                                                                                                                                                                                                                                                                            c.isDrawingMode = false;
                                                                                                                                                                                                                                                                                                                    c.selection = true;
                                                                                                                                                                                                                                                                                                                            setStatus("Select — tap a stroke to move or resize it.");
                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                          case TOOLS.LASSO:
                                                                                                                                                                                                                                                                                                                                                  c.isDrawingMode = false;
                                                                                                                                                                                                                                                                                                                                                          c.selection = false;
                                                                                                                                                                                                                                                                                                                                                                  // Lasso interaction is not implemented yet; the canvas is
                                                                                                                                                                                                                                                                                                                                                                          // intentionally inert, so say so rather than leaving it silent.
                                                                                                                                                                                                                                                                                                                                                                                  setStatus("Lasso — not implemented yet. Canvas is inactive in this mode.");
                                                                                                                                                                                                                                                                                                                                                                                          break;
                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                c.discardActiveObject();
                                                                                                                                                                                                                                                                                                                                                                                                                    c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                      }, [tool]);

                                                                                                                                                                                                                                                                                                                                                                                                                        function clearCanvas() {
                                                                                                                                                                                                                                                                                                                                                                                                                            const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                    c.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                        c.backgroundColor = "#ffffff";
                                                                                                                                                                                                                                                                                                                                                                                                                                            c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                setLayers([]);              // clear() may not emit per-object removal events
                                                                                                                                                                                                                                                                                                                                                                                                                                                    setStatus("Cleared.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        function deleteSelected() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const active = c.getActiveObjects();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!active.length) { setStatus("Nothing selected."); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            active.forEach((o) => c.remove(o));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c.discardActiveObject();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setStatus(`Deleted ${active.length} object(s).`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={page} ref={wrapperRef}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>Canvas</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={toolBarStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={btn(tool === TOOLS.SELECT)} onClick={() => setTool(TOOLS.SELECT)}>Select</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button style={btn(tool === TOOLS.BRUSH)} onClick={() => setTool(TOOLS.BRUSH)}>Brush</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={btn(tool === TOOLS.LASSO)} onClick={() => setTool(TOOLS.LASSO)}>Lasso</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button style={btn(false)} disabled>Mask (soon)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={btn(false)} onClick={deleteSelected}>Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button style={btn(false)} onClick={clearCanvas}>Clear</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ border: "1px solid #ccc", display: "inline-block", touchAction: "none" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <canvas ref={canvasElRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <pre style={{ whiteSpace: "pre-wrap", fontSize: 13 }}>{status}</pre>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>Layers ({layers.length})</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {layers.map((l, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={l.uid}>Layer {i + 1}: {l.type}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link to="/">Back to Home</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }