// src/Canvas.jsx
import { useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import * as fabric from "fabric";
import { db } from "./db";

const page = { padding: 24, fontFamily: "system-ui" };
const toolBarStyle = { display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" };
const btn = (active) => ({
  padding: "10px 14px",
    border: active ? "2px solid #333" : "1px solid #ccc",
      background: active ? "#eee" : "#fff",
        borderRadius: 6,
        });

        const TOOLS = { SELECT: "select", BRUSH: "brush", LASSO: "lasso" };

        let uidCounter = 0;
        const nextUid = () => `obj_${++uidCounter}`;

        export default function Canvas() {
          const canvasElRef = useRef(null);
            const fabricCanvasRef = useRef(null);
              const wrapperRef = useRef(null);
                const frameIdRef = useRef(null);
                  const dirtyRef = useRef(false);

                    const [searchParams] = useSearchParams();
                      const projectId = Number(searchParams.get("project")) || null;

                        const [status, setStatus] = useState("Initializing…");
                          const [tool, setTool] = useState(TOOLS.BRUSH);
                            const [layers, setLayers] = useState([]);
                              const [dirty, setDirty] = useState(false);

                                useEffect(() => {
                                    let cancelled = false;
                                        const width = wrapperRef.current?.clientWidth || 320;
                                            const height = Math.round(width * 1.4);

                                                // Canvas is constructed SYNCHRONOUSLY so cleanup always has a real
                                                    // instance to dispose, even if the async load below is still pending.
                                                        let canvas;
                                                            try {
                                                                  canvas = new fabric.Canvas(canvasElRef.current, {
                                                                          width, height,
                                                                                  backgroundColor: "#ffffff",
                                                                                          enableRetinaScaling: true,
                                                                                                  isDrawingMode: true,
                                                                                                          selection: false,
                                                                                                                });
                                                                                                                    } catch (err) {
                                                                                                                          setStatus(`Canvas failed: ${err.name} — ${err.message}`);
                                                                                                                                return;
                                                                                                                                    }

                                                                                                                                        canvas.freeDrawingBrush = new fabric.PencilBrush(canvas);
                                                                                                                                            canvas.freeDrawingBrush.width = 4;
                                                                                                                                                canvas.freeDrawingBrush.color = "#111111";
                                                                                                                                                    fabricCanvasRef.current = canvas;

                                                                                                                                                        const refreshLayers = () => {
                                                                                                                                                              setLayers(canvas.getObjects().map((o) => {
                                                                                                                                                                      if (!o.uid) o.uid = nextUid();
                                                                                                                                                                              return { uid: o.uid, type: o.type };
                                                                                                                                                                                    }));
                                                                                                                                                                                        };
                                                                                                                                                                                            const markDirty = () => { dirtyRef.current = true; setDirty(true); };

                                                                                                                                                                                                canvas.on("object:added", () => { refreshLayers(); markDirty(); });
                                                                                                                                                                                                    canvas.on("object:removed", () => { refreshLayers(); markDirty(); });
                                                                                                                                                                                                        canvas.on("object:modified", markDirty);

                                                                                                                                                                                                            (async () => {
                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                          if (!projectId) {
                                                                                                                                                                                                                                    setStatus("No project selected — drawing will not be saved.");
                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                              const project = await db.projects.get(projectId);
                                                                                                                                                                                                                                                                      if (cancelled) return;
                                                                                                                                                                                                                                                                              if (!project) { setStatus(`Project ${projectId} not found.`); return; }

                                                                                                                                                                                                                                                                                      const existingFrameId = project.frameIds?.[0] ?? null;
                                                                                                                                                                                                                                                                                              if (existingFrameId != null) {
                                                                                                                                                                                                                                                                                                        const frame = await db.frames.get(existingFrameId);
                                                                                                                                                                                                                                                                                                                  if (cancelled) return;                 // canvas may be disposed by now
                                                                                                                                                                                                                                                                                                                            if (frame?.layerData) {
                                                                                                                                                                                                                                                                                                                                        frameIdRef.current = existingFrameId;
                                                                                                                                                                                                                                                                                                                                                    await canvas.loadFromJSON(frame.layerData);
                                                                                                                                                                                                                                                                                                                                                                if (cancelled) return;
                                                                                                                                                                                                                                                                                                                                                                            canvas.backgroundColor = "#ffffff";
                                                                                                                                                                                                                                                                                                                                                                                        canvas.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                    refreshLayers();
                                                                                                                                                                                                                                                                                                                                                                                                                dirtyRef.current = false;
                                                                                                                                                                                                                                                                                                                                                                                                                            setDirty(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                        setStatus(`Loaded "${project.title}".`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setStatus(`New drawing for "${project.title}".`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!cancelled) setStatus(`Load failed: ${err.name} — ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cancelled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fabricCanvasRef.current = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Promise.resolve(canvas.dispose()).catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, [projectId]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Warn before a page reload or tab close with unsaved work.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const handler = (e) => { if (dirtyRef.current) { e.preventDefault(); e.returnValue = ""; } };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.addEventListener("beforeunload", handler);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => window.removeEventListener("beforeunload", handler);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  switch (tool) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case TOOLS.BRUSH:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c.isDrawingMode = true; c.selection = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setStatus("Brush — drag to draw."); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              case TOOLS.SELECT:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c.isDrawingMode = false; c.selection = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setStatus("Select — tap a stroke to move or resize it."); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case TOOLS.LASSO:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c.isDrawingMode = false; c.selection = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setStatus("Lasso — not implemented yet. Canvas is inactive in this mode."); break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          default: break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c.discardActiveObject();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, [tool]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          async function saveDrawing() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!projectId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setStatus("Cannot save — no project selected. Open a project from the Vault.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const layerData = c.toJSON();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (frameIdRef.current != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db.frames.update(frameIdRef.current, { layerData });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const newFrameId = await db.frames.add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      characterId: null, order: 0, layerData, createdAt: new Date(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      frameIdRef.current = newFrameId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const project = await db.projects.get(projectId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await db.projects.update(projectId, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                frameIds: [...(project.frameIds ?? []), newFrameId],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dirtyRef.current = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setDirty(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setStatus(`Saved at ${new Date().toLocaleTimeString()}.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setStatus(`Save failed: ${err.name} — ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function deleteSelected() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const objs = c.getActiveObjects();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!objs.length) { setStatus("Nothing selected."); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      objs.forEach((o) => c.remove(o));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c.discardActiveObject();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setStatus(`Deleted ${objs.length} object(s).`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function clearCanvas() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const c = fabricCanvasRef.current;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!c) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!window.confirm("Clear the whole canvas?")) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c.backgroundColor = "#ffffff";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              c.requestRenderAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setLayers([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setStatus("Cleared.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={page} ref={wrapperRef}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Canvas {dirty && <span style={{ color: "#c00", fontSize: 14 }}>• unsaved</span>}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={toolBarStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={btn(tool === TOOLS.SELECT)} onClick={() => setTool(TOOLS.SELECT)}>Select</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button style={btn(tool === TOOLS.BRUSH)} onClick={() => setTool(TOOLS.BRUSH)}>Brush</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={btn(tool === TOOLS.LASSO)} onClick={() => setTool(TOOLS.LASSO)}>Lasso</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button style={btn(false)} disabled>Mask (soon)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={btn(false)} onClick={deleteSelected}>Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button style={btn(false)} onClick={clearCanvas}>Clear</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={{ ...btn(false), fontWeight: "bold" }} onClick={saveDrawing}>Save</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ border: "1px solid #ccc", display: "inline-block", touchAction: "none" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <canvas ref={canvasElRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <pre style={{ whiteSpace: "pre-wrap", fontSize: 13 }}>{status}</pre>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>Layers ({layers.length})</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {layers.map((l, i) => <li key={l.uid}>Layer {i + 1}: {l.type}</li>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginTop: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link to="/vault">Back to Vault</Link>{" · "}<Link to="/">Home</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }